Fix version conflict causing plone 5.1.x buildout to fail
4teamwork/ftw-buildouts pull request #195
Opened 2021-03-15 09:51 UTC by Nachtalb

The latest version of "importlib-metadata" wants newer "typing-extensions".
If it takes the newest version it will require a newer version of "typing" as
well, which however is restricted to 3.6.2 by Plone.

Example fail: https://ci.4teamwork.ch/builds/413934/tasks/727082
Importlib: https://github.com/python/importlib_metadata/blob/5c9198cd8212d56db8ee9c49ee39a0980d11f5ff/setup.cfg#L23
Typing-Extension: https://github.com/python/typing/blob/ea7f88e8d2dd28a5569b2385c21b17063c480c7f/typing_extensions/setup.py#L69

2021-03-17 18:54 UTC, djowett-ftw requested changes
I'm not convinced ... the following commit implies you want to be pinning importlib-metadata < 3.0 

https://github.com/python/importlib_metadata/commit/107f9029fd5807c6579b881db19e11a0488f0675

2021-03-17 18:55 UTC, Nachtalb commented
@djowett-ftw I didn't see that one, you're right.

2021-03-18 11:28 UTC, Nachtalb commented
@djowett-ftw I updated the commit and the PR accordingly.

2021-03-18 15:09 UTC, lukasgraf approved these changes
I honestly can't judge possible consequences of this without investing a lot of time to test this.

But in principle it looks good. So I'd say go for it 👍 , we can always revert if it turns out to cause unforseen issues.

2021-03-19 08:54 UTC, djowett-ftw approved these changes
Looks. Good. To. Me. :-)

2021-03-19 09:53 UTC, merged